repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ['--profile', 'black']
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--ignore, "E501,W503"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        additional_dependencies: [
            pyzmq==25.0.0,
            betterproto==2.0.0b5,
            diopter==0.0.21,
            /local/home/ibricchi/pyllinliner
        ]
        args: [--strict]
